name: Update Jira Fix Version

on:
  workflow_dispatch:
    inputs:
      jira_fix_version:
        description: 'Jira Fix Version'
        required: true
      latest_release_tag:
        description: 'Latest Release Tag'
        required: true
  create:
    branches:
      - 'rc/[0-9]+.[0-9]*'
      - 'hotfix/[0-9]+.[0-9]*'
  push:
    branches:
      - 'rc/[0-9]+.[0-9]*'
      - 'hotfix/[0-9]+.[0-9]*'
    paths-ignore:
      - 'readme.md'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - 'readme.md'
      - 'README.md'
      - 'LICENSE'

jobs:
  sync-version-with-jira-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Checkout
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: '0'
      - name: Checkout
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/requirements.txt
      - name: Update Jira Issues
        run: python3 -c "$(wget -q -O - https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/main.py)"
        env:
          JIRA_SERVER: ${{ vars.JIRA_SERVER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_FIX_VERSION: ${{ inputs.jira_fix_version }}
          LATEST_RELEASE_TAG: ${{ inputs.latest_release_tag }}
